apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k-ocr-temp-storage
  namespace: k-ocr
  labels:
    app.kubernetes.io/name: k-ocr-web-corrector
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k-ocr-app-logs
  namespace: k-ocr
  labels:
    app.kubernetes.io/name: k-ocr-web-corrector
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k-ocr-ocr-models
  namespace: k-ocr
  labels:
    app.kubernetes.io/name: k-ocr-web-corrector
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard

---
# Redis Data PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k-ocr-redis-data
  namespace: k-ocr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: fast-ssd

---
# PostgreSQL Data PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k-ocr-postgres-data
  namespace: k-ocr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard